project:
  type: manuscript
  # execute-dir: project
  output-dir: docs
  render: 
    - index.qmd


manuscript:
  article: index.qmd
  resources:
    - data/research-paper-data-20241029.Rdata
    - data/research-paper-data-20241029.csv
    - data/survey_codebook.csv
    - data/data_dictionary.csv
    - data/raw_spss_sanitized_data_dict.csv
    - data/vmf_election_worker_recruitment_survey_raw_spss_sanitized_20241029_T12.02.sav
  code-links: 
    - text: Data Processing Script
      icon: file-code
      href: src/01-data-clean-process.R
      url: https://github.com/isaiahespi/rea-paper/blob/46e4c82d3685e3f9c62d64c7a6b4504742232f78/src/01-data-clean-process.R
  notebooks:
    - notebook: notebooks/figures.qmd
      title: "Figures"
    # - notebook: notebooks/01-data-import-clean-process.qmd
    #   title: "Data Import and Clean"

authors:
  - name: Isaiah Espinoza
    email: gespinoz@umd.edu
    roles: author
    affiliation:
      - name: University of Maryland
        department: Department of Government and Politics
        city: College Park
        state: MD
        country: US

bibliography: references.bib
csl: american-political-science-association.csl
# mainfont: Palatino Linotype
date-modified: last-modified
date-format: "YYYY-M-D"
notebook-links: false

knitr: 
  opts_chunk: 
    dev: "ragg_png" # same as knitr::opts_chunk$set(dev = "ragg_png")

format:
  bookup-html: 
    toc: true
    toc-depth: 3
    embed-resources: false
    embed-fonts: true
    link-citations: true
    smooth-scroll: true
    link-external-newwindow: true
    fig-cap-location: top
    html-math-method: mathjax
    notebook-links: global
    citations-hover: true
    footnotes-hover: false
    theme: 
      light: [bookup.scss]
      dark: [bookup.scss, bookup_dark.scss]
  #     
  aog-article-pdf:
    pdf-engine: latexmk
    keep-tex: false
    papersize: letter
    # mainfont: Palatino Linotype
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    linestretch: 1.25
    colorlinks: true
    urlcolor: RoyalBlue
    link-citations: true
    geometry: margin=1in
    cap-location: top
    fig-height: 4  # smaller fig heights make floating easier
    fig-width: 7.5 # set to the (full width - margins) of letter 
    fig-pos: '!t'
    hyperrefoptions:
      - pdfwindowui
      - pdfpagemode=FullScreen
    reference-location: document
    include-in-header: 
      - text: |
          \usepackage{dcolumn}

  # submittable-pdf:
  #   keep-tex: false
  #   endnotes: false
  #   titlepage: false
  #   mainfont: TeX Gyre Pagella
  #   mathfont: TeX Gyre Pagella Math
  #   fig-height: 4
  #   fig-width: 7.5
  #   cap-location: top
  #   fontsize: 12pt
  #   linestretch: 1.25
  #   papersize: letter
  #   link-citations: true
  #   colorlinks: true
  #   urlcolor: RoyalBlue
  #   include-in-header: 
  #     - text: |
  #         \usepackage{dcolumn}
  #         \usepackage{booktabs}

  # submittable-docx:
  #   keep-md: false
  # preprint-typst: 
  #   mainfont: Libertinus Serif
  #   running-head: Running head # preprint-typst format
  #   bibliography: references.bib
  #   bibliographystyle: "chicago-author-date"

  # docx: default
  # jats: default

  # (other formats)
  # pdf: 
  #   pdf-engine: latexmk
  #   pdf-engine-opts: 
  #     - xelatex
  #   documentclass: scrartcl
  #   keep-tex: false
  #   # mainfont: Palatino Linotype
  #   mainfont: TeX Gyre Pagella
  #   mathfont: TeX Gyre Pagella Math
  #   fontsize: 11pt
  #   indent: true # indented paragraphs (indent=true) vs space between paragraphs
  #   linestretch: 1.25
  #   number-sections: false
  #   citecolor: RoyalBlue
  #   cap-location: top
  #   fig-height: 4
  #   fig-width: 7.5
  #   link-citations: true
  #   papersize: a4
  #   geometry:
  #     - inner=3cm
  #     - outer=4cm
  #     - top=3cm
  #     - bottom=4cm
  #     - headsep=22pt
  #     - headheight=11pt
  #     - footskip=33pt
  #     - ignorehead
  #     - ignorefoot
  #     - heightrounded
  #   include-in-header: 
  #     - include-in-header.tex
  #   template-partials:
  #     - title.tex
  #     - before-body.tex

format-links:
    - format: bookup-html
      text: HTML
    - format: aog-article-pdf
      text: PDF
      icon: file-pdf
    # - format: submittable-pdf
    #   text: Submission Style PDF
    #   icon: file-pdf

execute:
  freeze: auto


