project:
  type: manuscript
  execute-dir: project
  output-dir: docs
  render: 
    - index.qmd

# learn about quarto manuscript project here https://quarto.org/docs/manuscripts/

manuscript:
  article: index.qmd
  manuscript-url: https://isaiahespi.github.io/rea-paper/
  resources:
    - data/research-paper-data-20241029.Rdata
    - data/research-paper-data-20241029.csv
    - codebooks/survey_codebook.csv
    - codebooks/data_dictionary.csv
    - codebooks/raw_spss_sanitized_data_dict.csv
    - data/vmf_election_worker_recruitment_survey_raw_spss_sanitized_20241029_T12.02.sav
  code-links: repo
  notebooks:
    - notebook: notebooks/figures.qmd
      title: "Figures"
    # - notebook: notebooks/01-data-import-clean-process.qmd
    #   title: "Data Import and Clean"
  

execute:
  freeze: auto

# set some YAML stuff that will be default for all documents.
# See: https://quarto.org/docs/projects/quarto-projects.html#shared-metadata
authors:
  - name: Isaiah Espinoza
    email: gespinoz@umd.edu
    roles: author
    affiliation:
      - name: University of Maryland
        department: Department of Government and Politics
        city: College Park
        state: MD
        country: US

bibliography: references.bib
csl: american-political-science-association.csl
# mainfont: Palatino Linotype # My fav, but no dedicated math font :(
date-modified: last-modified
date-format: "YYYY-M-D"
notebook-links: false

# set the custom `ragg_png` graphics device 
# see https://yjunechoe.github.io/posts/2021-06-24-setting-up-and-debugging-custom-fonts/
knitr: 
  opts_chunk: 
    dev: "ragg_png" # same as knitr::opts_chunk$set(dev = "ragg_png")

format:
  html: 
    toc: true
    toc-depth: 3
    mainfont: TeX Gyre Pagella
    sansfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    monofont: Inconsolata
    fontsize: 12pt
    cap-location: top
    page-layout: article
    appendix-style: none
    lightbox: true
    html-math-method: katex
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    notebook-links: global
    citations-hover: true
    footnotes-hover: true
    repo-url: https://github.com/isaiahespi/rea-paper
    csl: american-political-science-association.csl
    reference-location: document
    crossref: 
      ref-hyperlink: true
    other-links:
      - text: Survey Codebook
        icon: filetype-csv
        href: codebooks/survey_codebook.csv
      - text: Dataframe Dictionary
        icon: filetype-csv
        href: codebooks/data_dictionary.csv
      - text: Raw Dataset Dictionary (Sanitized)
        icon: filetype-csv
        href: codebooks/raw_spss_sanitized_data_dict.csv
    
    code-links:
      - text: Data Processing Script
        icon: file-code
        href: https://github.com/isaiahespi/rea-paper/blob/main/src/01-data-clean-process.R
    theme:
      light: flatly
      dark: darkly

  aog-article-pdf:
    pdf-engine: latexmk
    keep-tex: true
    keep-md: false
    papersize: letter
    # mainfont: Palatino Linotype
    mainfont: TeX Gyre Pagella
    sansfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    linestretch: 1.25
    colorlinks: true
    urlcolor: RoyalBlue
    link-citations: true
    geometry: margin=1in
    cap-location: top
    fig-height: 4  # smaller fig heights make floating easier
    fig-width: 7.5 # set to the (full width - margins) of letter 
    fig-pos: '!t'
    hyperrefoptions:
      - pdfwindowui
      - pdfpagemode=FullScreen
    reference-location: document
    include-in-header: 
      - text: |
          \usepackage{dcolumn}
          \usepackage{etoolbox}
          \AtBeginEnvironment{longtblr}{\begin{singlespacing}}
          \AtEndEnvironment{longtblr}{\end{singlespacing}}
  
  submittable-docx: default
  hikmah-response-typst:
    toc: false
    mainfont: TeX Gyre Pagella
    bibliography: references.bib
    bibliographystyle: american-political-science-association.csl
  # jats: default
  # docx:
  #   toc: false
  #   keep-md: true
  #   execute:
  #     echo: false
  #     eval: false
  #     include: false
    


