project:
  type: manuscript
  output-dir: docs
  render: 
    - index.qmd

manuscript:
  article: index.qmd

bibliography: references.bib
csl: american-political-science-association.csl
mainfont: Palatino Linotype
date-modified: last-modified
date-format: "YYYY-M-D"

format:
  bookup-html: 
    toc: true
    toc-depth: 3
    embed-resources: true
    embed-fonts: true
    link-citations: true
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    theme: 
      light: [bookup.scss]
      dark: [bookup.scss, bookuo_dark.scss]
  # docx: default
  jats: default

  # (other formats)
  # pdf: default
  # aog-article-pdf:
  #   keep-tex: false
  #   mainfont: Palatino Linotype
  #   urlcolor: RoyalBlue
  submittable-pdf:
    keep-tex: false
    endnotes: false
    titlepage: false
  submittable-docx:
    keep-md: false
  # preprint-typst: 
  #   mainfont: Libertinus Serif
  #   running-head: Running head # preprint-typst format
  #   bibliography: references.bib
  #   bibliographystyle: "chicago-author-date"

format-links:
    - html
    - format: submittable-pdf
      text: PDF
      icon: file-pdf
    - format: submittable-docx
      text: MS Word
      icon: file-word
execute:
  freeze: auto



