project:
  type: manuscript
  output-dir: docs
  render: 
    - index.qmd
    - "!notebooks/01-data-import-clean-process.qmd"
    - "!notebooks/02-tables.qmd"
    - "!notebooks/03-figures.qmd"
    - "!notebooks/question-set-differences.qmd"

manuscript:
  article: index.qmd
  resources:
    - data/research-paper-df-20250203.Rdata
    - data/survey_codebook.csv
    - data/data_dictionary.csv
    - data/raw_spss_dict.csv
  code-links: 
    - text: Data Import Script
      icon: file-code
      href: src/01-data.R
      url: https://github.com/isaiahespi/rea-paper/blob/0bd7138259d244e9a046828fdcf09f2a33837b95/src/01-data.R
  # notebooks: 
  #   - notebook: notebooks/01-data-import-clean-process.qmd
  #     title: "Data Import and Clean"
  #   - notebook: notebooks/02-tables.qmd

bibliography: references.bib
csl: american-political-science-association.csl
mainfont: Palatino Linotype
date-modified: last-modified
date-format: "YYYY-M-D"
notebook-links: false

format:
  bookup-html: 
    toc: true
    toc-depth: 3
    embed-resources: false
    embed-fonts: true
    link-citations: true
    smooth-scroll: true
    link-external-newwindow: true
    notebook-links: global
    citations-hover: true
    footnotes-hover: false
    theme: 
      light: [bookup.scss]
      dark: [bookup.scss, bookup_dark.scss]
  # docx: default
  jats: default

  # (other formats)
  pdf: 
    pdf-engine: xelatex
    documentclass: scrartcl
    keep-tex: false
    # mainfont: Palatino Linotype
    mainfont: TeX Gyre Termes
    mathfont: TeX Gyre Termes Math
    fontsize: 11pt
    indent: true # indented paragraphs (indent=true) vs space between paragraphs
    linestretch: 1.5
    number-sections: false
    citecolor: RoyalBlue
    cap-location: top
    fig-height: 4
    fig-width: 7.5
    link-citations: true
    papersize: a4
    geometry:
      - inner=3cm
      - outer=4cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    include-in-header: 
      - include-in-header.tex
    template-partials:
      - title.tex
      - before-body.tex
      
  #     
  aog-article-pdf:
    keep-tex: false
    papersize: letter
    # mainfont: Palatino Linotype
    mainfont: TeX Gyre Termes
    mathfont: TeX Gyre Termes Math
    colorlinks: true
    urlcolor: RoyalBlue
    link-citations: true
    geometry: margin=1in
    cap-location: top
    fig-height: 4  # smaller fig heights make floating easier
    fig-width: 7.5 # set to the (full width - margins) of letter 
    fig-pos: '!t'
    hyperrefoptions:
      - pdfwindowui
      - pdfpagemode=FullScreen
    reference-location: document

  submittable-pdf:
    keep-tex: false
    endnotes: false
    titlepage: false
    fontsize: 11pt
    linestretch: 1
    papersize: a4
    link-citations: true
    colorlinks: true
    urlcolor: RoyalBlue

  submittable-docx:
    keep-md: false
  # preprint-typst: 
  #   mainfont: Libertinus Serif
  #   running-head: Running head # preprint-typst format
  #   bibliography: references.bib
  #   bibliographystyle: "chicago-author-date"

format-links:
    - html
    - format: submittable-pdf
      text: PDF
      icon: file-pdf
    - format: submittable-docx
      text: MS Word
      icon: file-word
execute:
  freeze: auto



