---
title: "Response to Reviewers"
format: 
  hikmah-response-typst:
    toc: false
    mainfont: TeX Gyre Pagella
    bibliography: references.bib
    bibliographystyle: american-political-science-association.csl
    
---

I thank the Reviewers for taking time to provide their thoughtful and constructive comments. The Reviewers' comments are cited or summarized in [red italicized text]{.memo-reviewer-inline}, and my responses are in black Roman text. I also include excerpts from my revised manuscript in [blue]{.memo-excerpt-inline}.

# General Reviewer concerns on theory and competing explanations

Both reviewers' concerns touched on the same general issue, and the offered critiques and recommendations complemented each other. *Reviewer 1*{.memo-reviewer-inline} notes a general lack of discussion on potential explanations or explicit conjecture on a potential mechanism. **Reviewer 2**{.memo-reviewer-inline} recognized the same as ambiguity within of the theory; synthesis of the context (i.e., background section) and the literature didn't lead to a clear and concise reason for "why veterans" would be expected to influence confidence in elections. I dedicated a separate section titled as such hoping to clarify the source of my stated expectations, however I agree that the issue needs to be expounded at both ends. 

These added revisions are extensive, yet I believe adding a refined theory section and discussion section addresses the most immediate concerns raised by both reviewers. The theory section is revised to make clear "why veterans", noting the gaps in available literature while making the intent of the current study explicit; whereas the added discussion section complements the theory section by discussing potential explanations. 

::: {.memo-reviewer}
***Reviewer 1***---***what is the mechanism here?***: We understand that veterans are generally viewed positively, and that’s part of why this approach might work. However, in the data, we don’t see any direct measures of how respondents feel about veterans—there’s no pre-treatment baseline for that. I understand that the data might not allow for it, or that asking upfront could interfere with the treatment, but still---it leaves us wondering: what exactly is driving the results? Is it the idea of integrity, a feeling of safety or strength, or a sense of national service? We don’t really know. For this paper, it might be acceptable to say we’re building on prior work and that the cue is sufficient, but it would be helpful to acknowledge that gap more directly and discuss potential explanations.
:::

In response to *Reviewer 1*'s{.memo-reviewer-inline} concerns, I extend a discussion prior to the conclusion in order address potential explanations as avenues for future research. 

::: {.memo-excerpt}
The bluntness of the experimental stimulus and survey items don't allow us to establish exactly what it is about military veterans in particular that cues stronger confidence in elections. No survey items assessed public attitudes about military veterans specifically, pre- nor post-treatment. This unfortunately leaves no room for me to postulate and examine any potential mechanisms underlying results. As such, a question lingers about whether some antecedent mechanism transmits (i.e., mediates) the effects of the veteran treatment vignette to the outcome. To put simply, this study reiterates that there *is* something special about veterans in particular that elicits greater confidence in elections, but cannot go further in determining exactly *what* that special something might be.

Factors that *moderate* the relationship of the treatment on the outcome of interest are likely plenty, but one can only offer conjecture of a *mediator* driving results. One potential explanation is that veterans, and all those who serve in the military, potentially function as a national symbol. The group is abstract just as the nation is abstract, and the potency of the veteran group emulates the potency of a national symbol. Recall Benedict Anderson's [-@anderson2006] meditation on the Tomb of the Unknown Soldier, "...saturated with ghostly *national* imaginings" [-@anderson2006, 9, emphasis original]. In various studies, national symbols such as the flag, the national anthem, or even mere appeal to national identity have potent, yet variable, effects on different outcomes [@schatz2007; @butz2007; @kemmelmeier2008; @butz2009; @gangl2016; @kalmoe2016; @levendusky2018]. It is plausible that military service members and veterans function in much the same way---as a symbol of national loyalty, pride, and nationalism for people to praise and revere out of a sense of duty prescribed by social norm and reinforced by national sentiment. As such, it may be the case that the treatment effect on confidence in elections is mediated through an affective response to a national symbol---in this case, veterans. The veteran cue may indeed stimulate national sentiment and subsequently boost confidence in elections.

In results presented here, confidence in elections is associated with greater confidence among those in the treatment group, but neither vignette conveys information about the procedures or practices meant to safeguard election integrity; nothing in the treatment suggests to respondents that election integrity would be improved by recruiting veterans. Arguably, the results presented here speak to the "emotional pathway" mentioned in @gaudette2025 so long as we assume that there's an inherent appeal to national sentiment (e.g., nationalism, patriotism) by use of veterans[^13]. Importantly, if the veterans treatment is mediated by stimulation of affect for nation or national identity, then comparable stimulation of national sentiment unrelated to veterans should produce similar results via this "emotional-pathway". However, appeals to national sentiment by use of sterile national symbols (e.g., banal presentation of the U.S. flag, playing of the national anthem) may not have the same affective influence on confidence in elections. 

[^13]: The study by @gaudette2025 included an experiment that examined the contrast between "emotional" versus "informational" appeals on trust in elections and beliefs that election fraud is prevalent. Authors presented one of two video messages created by election administration officials in either Virginia or Maricopa County, AZ; the former was "emotions-based" in that it provided little to no information about the voting process or election administration, whereas the latter provided, "...specific information about the processes used to ensure the integrity of the vote with no appeal to emotion or patriotism" [-@gaudette2025, 13].

In a similar vein, it is plausible that certain political apprehensions are nullified insofar as veterans as a group are generally perceived as 'apolitical'---which itself may be enough to engender favor among the mass public [@krupnikov2022]. Current and former military service members may be viewed by the public generally as 'apolitical', especially in comparison to practically any other social group. Indeed, an 'apolitical' reputation has been long desired by military leaders and top brass [@lagrone2019; @garamone2016; @garamone2016a; @baldor2020] despite evidence to the contrary [@betros2001; @mcnerney2006]. Nevertheless, the putative 'apolitical' nature of military service may generalize to veteran service members, and increase confidence in elections based on the assumption that veterans uphold a commitment to ensure election integrity above their own personal loyalties, partisanship, or politics. Prior research has relied on the assumption that such a "*group-based*" norm persists among military members, which prescribes that the military is, or ought to be, apolitical [@mullinix2022]. Although, the extent to which this perception generalizes widely among the mass public about the military in general, or about current and former service members in particular, has yet to be examined. Given recent events of far more overt politicization of the U.S. military [@baldor2025; @baldor2025a; @baldor2025b; @baldor2025c; @thomas2025], it would be useful for future research to consider whether perceptions about the military generally, and military leaders in particular, generalize to perceptions about current and former military service members. Especially insofar as such attitudes relate to confidence in the electoral process and administration.
:::

::: {.memo-reviewer}
***Reviewer 1***---***Hypothesis structure could be clearer***: You present H1 very clearly, which is great. However, later in the paper, there are additional expectations that seem like they could have been articulated as formal hypotheses too—perhaps H2, H3, or even sub-parts like H1a, H1b. While it’s not a major issue, clearer hypothesis structure would enhance readability and help clarify the paper’s logic as it progresses. Currently, it feels like a mix of formal and informal framing.
:::

Agreed. The revised text follows below. 

::: {.memo-excerpt}

> H~2~: Differences in confidence in elections in one's local area and confidence in elections in Maricopa County, AZ, will be smaller among those who are presented with an announcement that election officials are recruiting miilitary service veterans to work as election staff and volunteers compared to those presented with an announcement of recruitment efforts that do not mention military veterans.

\dots

> H~3~: Among those who refute the legitimacy of the 2020 election results, those presented with an announcement that election officials are recruiting veteran service members for election jobs will be associated with greater levels of confidence in elections compared to those presented with an announcement of recruitment efforts that do not mention military veterans. 

Prior research has found that political candidates benefit from having a military background [@mcdermott2015], especially evaluations of candidate's prospective performance on particular war issues (e.g., foreign policy, terrorism) [@hardy2019]. The idea is that prior military service provides meaningful information to use as a heuristic in regard to such "war issues". Although veterans are no longer actively serving, there's potentially some lingering general assumptions about the capacities and motives of military veterans to provide safety and security arising from the nature of their prior occupation as members of the U.S. armed forces. Insofar as the physical safety of people at election sites is a "military matter", then the potential that election sites may be staffed with military veterans may ease related concerns about the safety and security of those places. As such, I expect that concerns about potential for violence will be lower, and confidence in voter safety higher, when presented with information that veterans are being actively recruited to work and volunteer in election offices.

> H~4a~: Concerns about the potential for violence, threats of violence, or intimidation while voting in person will be lower among those presented with an announcement that election officials are recruiting veteran service members for election jobs compared to those presented with an announcement of recruitment efforts that do not mention military veterans.

> H~4b~: Confidence that voters will be safe to vote in-person at election sites will be higher among those presented with an announcement that election officials are recruiting veteran service members for election jobs compared to those presented with an announcement of recruitment efforts that do not mention military veterans. 
:::

::: {.memo-reviewer}
***Reviewer 1***---***Racial dynamics and trust***: This aspect also emerged for me. The sample is mostly white, making it challenging to draw conclusions about how this might work for communities of color. As we know, these communities often have long histories of institutional distrust—including towards the military. Thus, it’s possible the cue might not resonate in the same way, or perhaps it does, as many veterans are people of color too. We don’t know, and the current data cannot address that limitation—but acknowledging it and speculating could be beneficial.
:::

::: {.memo-reviewer}
***Reviewer 2***---***Data and Methods***: Manipulation check: Was one included? If not, I’d recommend at least discussing this. How do we know that respondents interpreted the “veteran” cue as the author expects? Could it conflate with race, gender, or general views of the military?"
:::

::: {.memo-reviewer}
***Reviewer 2***---***Data and Methods***: Relatedly, might respondents be reacting not to “veteran” status *per se*, but to broader schemas about military discipline, patriotism, or law and order? If so, could this effect be amplified (or diluted) depending on the respondent’s background? These questions may not require new data but should be acknowledged and theorized.
:::

The above concerns raised by each reviewer are similar as they concern the potential for differential effects of the veterans cue. 

As for manipulation check, there were no *a priori* expectations regarding how respondents would cognitively interpret the veteran treatment vignette beyond what was stated in the hypotheses. Upon presentation of either the treatment or control vignette, survey respondents were unable to progress further in the survey until at least 15 seconds had elapsed. The survey included two "screener" items as an attention check prior to presenting either the treatment or control vignette. Respondents who failed to select a certain response twice in a row were removed from the survey.

In response, I included the following text in the revised discussion section.

::: {.memo-excerpt}
The data of the current study is limited in helping to discern whether the treatment garners greater confidence in elections uniformly across different racial or ethnic groups given that the largest proportion of the sample identified their race as White (77%). It is reasonable to suspect that the treatment vignette might differ by race and ethnicity, but the sample is insufficient to make such generalizations. Nevertheless, attitudes about veterans that differ by group may play an important role in determining whether publicized efforts to recruit military veterans boosts confidence in elections uniformly or whether the effect is merely partial to certain segments of the population. In their research examining whether groups differed in attitudes about veterans, @kleykamp2018 could only speculate as to why levels of support were lowest among Hispanic and Black respondents. Other research has found that attitudes about the U.S. military generally---though not about active or veteran military service members in particular---differs by race and ethnicity to varying extents, but could not supply reason for one groups' sentiment over another [@nichols2015]. 

Other studies have drawn out disparities in public attitudes about veterans but in ways that are mostly indirect, i.e., without assessing public regard for veterans directly. One overarching issue is that there's limited research that differentiates public regard for veteran and active military service members from the U.S. military as an institution in general. For instance, some studies assess public regard for veterans indirectly by examining whether, and to what extent, endorsement of certain policies differentiate by whether such policies benefit veterans or the public generally. In one such study, Republican partisanship was shown to be the most consistent factor associated with more favorable attitudes on homelessness and PTSD among the veteran population, but not among the general adult population [@tsai2021]. 

Perhaps unsurprisingly, military veterans appear to be uniquely deserving in the eyes of Republican partisans [@tsai2021; @mcdermott2015; @richardson2022]. As such, military veteran status may qualify favorable attitudes among Republican partisans whereas their regard for other non-veteran groups might otherwise express contempt or indifference. This further indicates a need for research to determine an underlying mechanism explaining why veterans incur special favor.
:::

::: {.memo-reviewer}
***Reviewer 1***---***How generalizable are these results***: I appreciate your honesty about how the strongest effects appear in Maricopa County, and that we don’t observe the same impact when people consider their own local elections. That’s interesting in itself, but it raises questions—can this approach be effective in other areas? Would appointing veterans as officials in lower-salience places have any impact? Or is this cue only meaningful in scrutinized locations? You touch on this briefly, but expanding this section would add depth, particularly for readers contemplating its implications for future elections.
:::

To address these concerns, I include the following text in the discussion

::: {.memo-excerpt}
As stated previously, the survey was fielded on a non-probability sample of 1,287 U.S. citizens 18 years of age or older. The results presented here are not assumed to be generalizable to the national population. It may be feasible to weigh the sample to demographics of the population at the time the survey was fielded, but this is unnecessary for the experimental purpose of the study. If similar findings complement or replicate these results, then the expense of drawing samples more representative of the national population may be justified. At this stage, however, the results are limited to demonstrating treatment effects that are sample dependent.

Note also that the measurement items of the components trust and distrust, and the method of computing scores for the dependent variable, confidence in elections, are unique to this study but falls under the methodological framework of Classical Test Theory (CTT). Although survey measurement items were either directly drawn from or inspired by similar survey items found in various other surveys (e.g., SPAE, Pew), the question wording, response choices, coding, and computation of sum scores of the dependent variable are specific, thus rendering measurement of the hypothetical constructs of interest (i.e., trust, distrust) less comparable across similar studies that profess measurement of similar constructs [@widaman2024]. Namely, trust, distrust, or confidence in elections as defined and measured here.

The setting of the vignette and specified in survey items might raise additional concerns on whether results are generalizable. Naming a specific county in the vignette adds in a potentially influential factor unaccounted for in the survey; some people may have attitudes about the county in question, others won't, while others may be muffed to consider a random county in the U.S. they know nothing about. Naming a real and somewhat salient county potentially undermines confidence that the treatment effects are solely attributable to veterans to an unknown degree. Simply put, there may be something special about Maricopa County, AZ in particular that generalizes across attitudes of trust or distrust in elections. 

Arguably, however, Maricopa County is indicated as the setting in both the treatment and control vignettes, thus the only actual difference between conditions is constrained to the target group being recruited. Future research may employ vignettes naming a fictional U.S. county to hopefully eliminate the setting as a concern. Alternatively additional survey items that ask directly about one's knowledge or sentiment about the county in question could inform researchers on whether the named county imposes any undue influence at all, or whether the setting is associated with other factors such as partisanship.
:::


## Reviewer 2

::: {.memo-reviewer}
***Reviewer 2***---***Theory***: "The author could be clearer about the puzzle: Why would identifying poll workers as veterans plausibly increase confidence in elections? Why might it not? The paper gestures at answers---trust, apolitical reputation, shared identity---but doesn’t quite fully develop the competing
expectations."
:::

In response to *Reviewer 2*'s comments concerning the theory, I restructure the theory section to incorporate the "Why veterans" section, expand on the premises, and add literature that better leads to the expectations. The text below reflects the revised theory section that better incorporates "Why Veterans".

::: {.memo-excerpt}
Election officials don't focus on recruiting people of a particular demographic, status, class, or prestige in order to shore up public trust in elections, and they don't discriminate recruitment efforts based on who the public thinks is best suited to secure elections from fraud.

Election officials are likely to be agnostic as to who dedicates their time to civil service such as election work. Especially since staffing has been an issue since at least the 1990s [@maidenberg1996; @ferrer2024]. In 2020, such efforts were made far more difficult by the COVID-19 pandemic [@mena2020; @abbate2020a]. There's no special reason to target veterans for recruitment above other groups. Indeed, there's no reason to discriminate recruitment efforts at all if the point is purely to fill staffing vacancies.

Veteran military service members are, after all, civilians; Civilians with shared (but varied) experience and status of prior military service, but who are no more or less qualified for this civil service^[Research is limited and mixed on whether veterans in general are more inclined, however [@nesbit2011].] than non-veteran civilians. To be frank, announcements about concerted efforts to recruit veterans as election workers should not reasonably influence one's trust that votes will be counted more accurately, or that election fraud will not occur; there is no known evidence demonstrating that actually employing veterans as election staff or volunteers further improves the safety, security, and overall integrity of elections in the United States. Moreover, there's no known evidence of positive influence on public perceptions of said outcomes when voters encounter military veterans working as staff or volunteers at elections sites. 

Rather, the claim that recruiting veterans to work as election staff and volunteers would improve public confidence in elections emerges as non-profit organizations---mainly comprised of veteran and military family members themselves---operate under, and promote, that assumption [@looker2024; @lawrence2024; @wentling2024]. Non-profit groups of late have made incredible strides in targeted recruitment efforts under the notion that veterans are uniquely capable, committed, and best fit to serve the needs of the United States as civil servants and volunteers at election sites. Indeed, this study can be seen as a test of a particular assumption that veterans have about themselves---the assumption that their mere presence and civic engagement will inspire confidence in elections among the public.

There was a sudden push to target veterans for recruitment efforts that arose shortly after the events on Capitol Hill on January 6th, 2021. After the 2020 election, large efforts were made to recruit military veterans and their families to work or volunteer as election staff [@wetheveterans2022; @nflfootballoperations2022]. Prior to that point, young people were sometimes given special mention as targets of election worker recruitment efforts [@powerthepolls2020; @herndon2020]. Generally, however, recruitment efforts cast a wide net, indiscriminate of who applies [@ross2020; @conde2020].

One can speculate that the motivation to associate military veterans with civic engagement and democracy may be intended to counter negative perceptions and impressions given by the proportion of veteran service members arrested for taking part in the events on January 6th [@milton2021; @loewenson2023; @jensen2022a]. Especially with regard to research demonstrating that willingness to support violent efforts to overturn election results (in support of Trump) is, on average, more common among veterans than among matched samples of non-veterans [@pape2024]. This is in addition to a strengthened association portrayed in media outlets between military veterans and militias [@steinhauer2020]. Prior research has substantiated such a connection between veterans and militia groups. @cooter2024 notes from her 3-year ethnographic fieldwork among Michigan militia members that, "...approximately 40% of militia leaders and 30% of members had previous military experience. Most of these veterans actively sought out such groups, as opposed to being recruited by them" [see also @cooter2013]. Thus, countering such associations by promoting a different image of veterans to the mass public and veterans alike seems like a reasonable motivation. Yet such speculation is just that.

The key findings of literature on confidence in elections hardly point to public regard for veterans as a mechanism for the theoretical expectations of improving overall confidence in elections and improving feelings of voter safety at election sites. Comparable research finds that confidence in elections is increased through elite rhetoric from fellow partisans affirming legitimacy of elections [@clayton2023], or through the provision of information about the electoral process or other official messaging of election officials themselves [@gaudette2025]. Neither of the studies just cited, however, consider attitudes or sentiment about veterans as a source for dispelling distrust and improving trust in elections. To be clear, there is no immediate "puzzle" in the literature that immediately draws out public sentiment for military veterans as a source for bolstering confidence in elections. That being said, the general public perception, attitudes, or even stereotypes about military veterans are significant to consider.

It is important to make clear two considerations that underpin the notion that information about veterans will improve trust and quell distrust in elections. First, positive public regard for veterans *in general* is sufficient to elicit greater trust and lower distrust in elections despite the fact that information about veterans as election workers, or even merely information on efforts to recruit veterans, has no bearing on the actual integrity of the electoral process. An underlying assumption here is that there *is* something special about veterans, but this doesn't include a proposition on exactly *what* that special something might be in theory. This is partly due to the limited research available on public regard for veterans, specifically in terms of elucidating an underlying mechanism for such positive favor. Moreover, there is limited research on public opinion about former and active military service members distinguished separately from public opinion about the military as an institution in general. Endorsement or support of government policies intended to benefit veterans specifically (e.g., federal funding on veteran healthcare) are easy to conflate as interchangeable with public attitudes about veterans as a group in particular. This, in turn, permits general expectations of positive influence due to the public's overarching positive regard for veterans, but disallows for expectations regarding how respondents would actually process and interpret a treatment that only mentions efforts to recruit them for election work. In short, we are sure that people sustain positive views for veterans generally, but beyond that I make no special effort to propose and examine why that is the case in greater detail.

The evidence that can be gathered concerning public regard for military veterans shows that, generally, veterans are perceived favorably among the general public; although military recruitment shows a downward trend as of late, public perceptions of veterans are overwhelmingly positive [@kleykamp2023]. In my review of the literature, I found only one study which assessed public opinion about veterans specifically and examined whether attitudes differed by group [@kleykamp2018]. @kleykamp2018 investigated the extent to which positive regard for military veterans in terms of both social distance and deservingness varies across different groups, and the extent to which such support is exaggerated. Their research found that levels of support for veterans tended to be predictably lowest, but also most exaggerated, among those who were younger and non-White. Determining what groups hold special favor for veterans still leaves it unclear as to what it is about veterans that engenders greater confidence in elections. Yet, generally, all groups expressed exaggerated support for veterans in more than one way [@kleykamp2018], suggesting that public regard for veterans is prescribed by widespread social norm.  

This is taken together with literature suggesting that public trust in elections is malleable to factors, experiences, events, or phenomena that range in logical relevance to the actual structure or administration of elections. On the one hand, public trust is, indeed, influenced by information specifically about the processes of conducting elections [@gaudette2025]. On the other hand, the public's trust in elections is not beholden to the demonstrated *trustworthiness* of the institution of election administration. Thus the first consideration is simply that the positive public regard for veterans in general may function sufficiently as a cue to elicit greater trust in elections despite relevance.

Second, veterans are a particularly potent group where mention of one's veteran status seems to have a positive, calming, or nullifying effect on attitudes. More so than just the general positive favor afforded to veterans, the group appears to have a somewhat pacifying effect on negative or otherwise contemptible discrimination, prejudice, and social stigma. For instance, recent research shows that, during his campaign in the 2020 Democratic Primaries, Pete Buttigieg's military background mitigated discrimination against him when he was presented as a veteran married to a man [@magni2024]. Similar research has also found that a candidate's veteran status affords them better evaluations regarding competency in particular issue areas (e.g., war competence) [@teigen2013; @hardy2019]. Moreover, veteran status seems to mitigate or nullify usual stigmas associated with mental illness. That is to say, there is negative stigma associated with mental illness [@corrigan2002] and such stigma incurs labor market discrimination [@hipes2016], but evidence suggests that veteran status overrides such stigma and discrimination [@maclean2014]. Or, in another light, mental illness is seemingly more *understandable* (i.e., permissible) for veterans given the presumptive reasons for their mental strife. And media framing as such plays an important role on public perception [@kleykamp2015]. Relatedly, attitudes about homelessness and PTSD---ranging from perceived causes of homelessness, whether the federal government should dedicate more resources, perceived effectiveness of policies, to compassion for homeless individuals---are generally more favorable for the homeless population among veterans than for the homeless population of general adults [@tsai2021]. Such effects primarily pertain to attitudes about individual people or groups (e.g., a political candidate, prospective employees, the homeless population). The capacity of one's veteran status to pacify prejudice, discrimination, and stigma likely extends out to quell negative and disfavorable attitudes regarding institutions to a similar extent, e.g., distrust. 

The question emerged in light of the recent surge of efforts nationwide to recruit veterans to serve as election workers [@lawrence2022; @wentling2024] midst an environment where election insecurities were heightened and intensified. Bearing that in mind, the heightened insecurities in anticipation of upcoming elections do not merely pertain to the election outcome (e.g., who wins), but to one's general sense of confidence in the integrity of elections administration and to the safety of casting a ballot in-person. 

Given the heightened tensions and electoral anxieties, the expectations surrounding the unique pacifying effect that veterans have on attitudes about individuals or other groups is extended to determine whether a similar effect is found when the target of one's consideration is not just a person or group but the institution of election administration itself. Thus the second consideration for "why veterans" are expected to dispel distrust in elections pertains to pacifying effect of negative or disfavorable attitudes observed in relevant literature. 

The stimulating influence of veterans as a group in the abstract is expected to counteract distrust and insecurity pertaining to the institution of elections administration, as well as inspire greater confidence in the same. There's scant research or evidence available to postulate a well-formed theory on the mechanism underlying the expected effects of veterans as a group on attitudes about institutions and processes, rather than on attitudes about persons or groups. What may be posited at best, however, is that distrust and insecurity in elections among the public is expectedly reduced to some extent through generally positive public regard for military veterans and their unique capacity to quell disfavorable attitudes.
:::

::: {.memo-reviewer}
***Reviewer 2***---***Theory***: Relatedly, I’d encourage the author to more clearly distinguish the scope conditions of this theory. For instance: Is this paper about elite signaling, political trust, or identity-based persuasion? Each of these frameworks could work, but right now they’re blended in a way that dilutes their force.
:::

In order to be more explicit, I added the following text.

::: {.memo-excerpt}
# Theory

This theory is constrained to public confidence in the administration of elections in the United States. To be clear, the scope conditions in which this theory applies concern public trust and distrust in election administration in the anticipatory period prior to the election event. Moreover, this study is, to a limited extent, indirectly related to public regard about veteran members of the U.S. Armed Forces.
:::

::: {.memo-reviewer}
***Reviewer 2***---***Theory***: Terms of art should be defined with precision. What do we mean by “voter confidence”? Is it about procedural trust? Belief in outcome integrity? Perceived impartiality? Greater clarity here will help structure the analysis and give readers clearer expectations.
:::

I agree with **Reviewer 2** and apologize for any confusion. In order to address the above concern, I inserted the following text which was initially cut from an earlier draft for length. This section follows the added text above within the theory section and also further addresses clarification of scope conditions.


::: {.memo-excerpt}
## Trust and Distrust in Elections

The theoretical relationship between trust and distrust is important to understand, especially when it comes to the dependent outcome of interest. Before going further, it is necessary to explicate the conception *confidence in elections* with respect to trust and distrust.

Trust is, after all, merely *belief* held in the face of uncertainty. Trust is reliance on the veracity of belief in the face of uncertainty. Said another way, trust is assured belief dependent on its supposed veracity; a state of certainty with respect to some belief or judgement. It is "assured" because it is one's belief that relies on something rather than nothing. Hence quantitative methods of the sciences are replete with things such as *confidence* intervals around our estimates. Therefore, I understand trust to refer to the state or quality of certainty around one's beliefs or expectations; the extent to which one is assured of their expectations regarding what is or what will be the case.

The kind of *trust in elections* I refer to concerns the expectations drawn up from one's judgement about the functioning of the electoral process---the extent to which one is assured in the belief that the electoral process will be fairly and accurately administered. I follow the notion of public trust in elections explicated by @stewart2022,

> "Public trust in U.S. election institutions comes down to whether voting machines accurately record votes, voter registration systems accurately record those eligible to vote, geographic information systems accurately assign voters to voting districts, election-night reporting systems accurately aggregate and communicate election results to officials and the public, and postelection audit and canvassing procedures proceed impartially and in accordance with the law." [-@stewart2022, 236]

That being said, I also account for expectations of electoral fraud, which I refer to as *distrust* in elections distinguished from trust. Distrust in this sense is also a belief, an expectation, about the anticipated functioning of the process. Note, however, that the prefix *dis-* in distrust implies "apart", "lack of, not" or "opposite". Conventionally, distrust is defined simply as the absence of trust, thus denoting a simple inverse and mutually exclusive relationship. However, as it concerns the psychology of an individual, *a lack of trust doesn't necessarily imply opposite expectations or opposing beliefs*. In particular, a lack of trust that votes will be accurately recorded, etc., doesn't necessarily imply inversely proportional expectations that electoral fraud will occur. In other words, although the relationship between trust and distrust is inverse, this relationship is not mutually exclusive. 

A person who is certain that electoral fraud will occur clearly lacks trust in elections; an expectation that electoral fraud will occur necessarily implies a lack of trust in elections regardless of positive expressions of trust. However, the reverse isn't also true; expressing a lack of trust in elections *doesn't necessarily imply* an expectation that electoral fraud will occur. Rather, a lack of trust implies an absence of assurance in the belief that the process will be conducted fairly and accurately---a lacking quality of certainty around said belief. An absence of such assurance denotes a state of *insecurity*. Other sources of uncertainty may challenge a person's confidence regarding the integrity of elections independent from anything that would lead them to believe electoral fraud will occur or has occurred. However my use of distrust refers to the assured belief that the outcome will be invalid---that outcomes will be independent of the process as prescribed, thus rendering outcomes as arbitrary. Specifically, distrust implies assurance in the belief that electoral fraud will occur.

As such, trust and distrust represent opposing degrees of confidence along the same spectrum. However, despite the inherent contrast, one can hold both positive degrees of trust and distrust, feeling relatively confident in both respects. Accordingly, *equivalent degrees of trust and distrust cancel out*, rendering one relatively more insecure about their expectations of the future despite the fact that they may report feeling confident in either direction respectively. When trust and distrust are considered reflective of one's confidence about future expectations, then both can be placed along the same spectrum. Therefore, a lack of confidence denotes insecurity.

This means that a person's baseline level of confidence in elections must take into account their present degree of distrust---i.e., their expectations of electoral fraud. Something may cause a person to have greater expectations that election fraud will occur, which in turn will always lower their trust in elections. In contrast, a person's trust in the integrity of the electoral process is reduced by the extent to which they expect that electoral fraud will occur.

Thus, it follows that a person distrusts the integrity of the electoral process to the extent that they are to some extent certain that electoral fraud will occur or has occurred. They are, perhaps, poised to discount election results as invalid or illegitimate in advance. Either way, both trust and distrust refer to some positive degree of confidence (i.e., assurance) regarding one's expectations. They are distinguished by reference to either the normative idea about what *should* come about, or what is *supposed* to come about given the logical structure and integrity of the process. If the structure and integrity of some process is coherent and secure, respectively, then the outcome that follows will be valid. Should the integrity of that process be damaged or opaque, then the process becomes vulnerable and validity of the results are open to challenge. With respect to the administration of U.S. elections, the confident voter expects that votes will be counted as voters intend, election staff will competently administer elections, election technology will be secure from nefarious tampering, and that the process will be fair for all involved.
:::



::: {.memo-reviewer}
***Reviewer 2***---***Data and Methods***: It would be helpful to know more about sample composition. How diverse is the sample in terms of veteran status, ideology, partisanship, and race? This will help the reader interpret the subgroup analyses.
:::


The following brief description of the sample was added prior to description of the survey design under the "Experiment Design and Survey Measures" section.

::: {.memo-excerpt}
The median age was $46$ (mean age was $47$), $51.13\%$ ($n = 658$) women, $46.46\%$ ($n = 598$) men, and approximately $1.24\%$ who identified as either Non-binary/third gender ($n = 7$) or preferred not to say ($n = 9$). The sample primarily identified as White or Caucasian $75.76\%$ ($n = 975$), while all other non-White respondents comprised $23.08\%$ ($n = 297$) of the sample. Those who held a graduate level degree (e.g., Master's, Doctorate, or Professional level) comprised $12.9\%$ ($n = 166$) of the sample; those with either degree at the Associate or Bachelor's level comprised $35.82\%$ ($n = 461$), while $21.99\%$ ($n = 283$) had some college but no degree; and $28.13\%$ ($n = 362$) had either a high school level or equivalent education or less than high school. The largest proportion of the sample were Democrat at $43.98\%$ ($n = 566$), followed by Republicans at $41.96\%$ ($n = 540$). The proportion of true Independents^[Independent 'leaners' were grouped into the respective party affiliation in which they lean.] was $12.59\%$ ($n = 162$).

Among the sample, $34.11\%$ ($n = 439$) said they had an immediately family member who was currently serving or had previously served in the U.S. military; $64.72\%$ ($n = 833$) didn't have a family member who served. Approximately $8.24\%$ ($n = 106$) of the sample were veterans, while $1.17\%$ ($n = 15$) reported to be actively serving. 
:::


::: {.memo-reviewer}
***Reviewer 2***---***Findings***: The author identifies heterogeneous effects by election level (local vs. national), which is a fascinating and potentially important finding. But what does this mean substantively? Do voters view the stakes of “local” and “national” elections differently with respect to legitimacy? Do they associate veterans with one level more than another?
:::

Despite the limitations noted previously, I added the text below in response to **Reviewer 2**'s concerns on the potential substantive significance of the findings. This text can be found just prior to the subsection "2020 Election Legitimacy Beliefs".

::: {.memo-excerpt}
The veteran cue is potentially compensatory, which supports the second hypothesis (H~2~). That is, the gap in confidence in local elections and elections in Maricopa County is reduced by the veterans cue, therefore compensating for the otherwise lower confidence and greater insecurity in Maricopa County elections. This is analogous to studies showing that Republicans support for a Democratic candidate is compensated by a Democratic candidate's veteran status. Hypothetical Democratic veteran candidates were more palatable to Republican partisans than non-veteran Democrats [@mcdermott2015]. Similarly, Democratic veterans received higher support in Senate races, especially Democratic veteran Senate candidates whose military experience included deployment to conflict zones [@richardson2022]. The point of note is that it is *Democratic* candidates who receive *more* of a benefit that comes with veteran status[^]; the analogy being that it is elections located elsewhere that receive the benefits of the veteran cue whereas local elections do not. Note that the results can't necessarily be read as differing between elections at the local level versus national level, but rather heterogeneous effects differ by elections at the local level and elections in Maricopa County, AZ. The compensatory effect of the veteran cue may generalize to other jurisdictions other than one's local area, or the effect may be confined to Maricopa County, AZ given that this specific county had been made especially salient in the past.

[^]: Note that the war veteran classification provided benefits to Republican Senate candidates vote share distinct from "common" veterans---i.e., Republican Senate candidates who did not deploy to areas of conflict [@richardson2022].
:::


::: {.memo-reviewer}
***Reviewer 2***---***Findings***: The author should consider the magnitude and directionality of effects in relation to expectations. For instance: Are the observed changes in confidence substantively meaningful? Are they comparable to known effects in this literature (e.g., from partisan cues or fraud frames)?
:::

While this is understandable, I was unable to compare magnitude of effects between comparable studies due to the differences in measurements across multiple studies examining trust or confidence in elections. I include the following text within the discussion to address this point.


::: {.memo-excerpt}
It is difficult to compare magnitude of effect with other studies given that the item number, item wording, measurement, and computation of confidence in elections is unique across most individual studies to include this one. For instance, @gaudette2025 doesn't compose multiple items into a single composite measure, but subtracts pre-treatment values from post-treatment values for single-item measures with Likert-style response options. Whereas @clayton2023 develops a scale referred to as "Trust in American electoral process" by taking the mean from three items. The item wording of that scale is markedly similar to the items used to compose the trust scale of this study, but the range of response options differs considerably. Thus, while most studies examining public confidence in elections often include the core question "How confidence are you that your vote \[will be/was\] counted as you intended in the most recent election?", the different ways that researchers measure and compute variable scores on the outcome are most often, and unfortunately, sample dependent. The study of public confidence in elections is in desperate need of a standard method of measurement, or even a screened and validated item bank, and this study may be seen as a baby step to that end.

That being said, this study generally emulates treatment effects of comparable studies in the literature. @gaudette2025 found positive effects of official messaging from election officials on various items measuring trust in elections and expectations of electoral fraud. Similarly, @clayton2023, confined to a sample of Republican participants, found positive influence on perceptions of 2020 election legitimacy and trust in the American electoral process from official messaging by Republican politicians reaffirming the 2020 election results.
:::


::: {.memo-reviewer}
***Reviewer 2***---***Findings***: I also encourage more discussion of null results. Even where effects are weak or absent, that tells us something important—especially if veteran cues only resonate among certain audiences or in certain electoral contexts.
:::

Although I am sympathetic to this view, results permitted rejection of the null hypotheses posited in the research paper. It was expected that the veteran cue would not influence confidence in local elections, which was described in the findings. Further discussion addressing this concern was added to the description of the findings and also addressed in the revised discussion section. 
