---
title: Tables
author: Isaiah
format: 
  html: 
    code-fold: false
    code-tools: true
    code-overflow: wrap
    code-copy: true
    code-annotations: true
---

```{r}
#| label: setup
#| include: false

# load packages
library(tidyverse)
library(datawizard)

# load data
load("data/research-paper-data-20241029.Rdata")

# load data dictionary/codebook
codebook <- read.csv("data/survey_codebook.csv")
data_dict <- read.csv("data/data_dictionary.csv")

# also load the raw data dict for comparison
raw_spss_dict <- read.csv("data/raw_spss_dict.csv")

```

```{r}
#| label: post_processing
#| include: false

# Some post-processing of the dataframe :::::::::::::::::::::::::::::::::::::###

# code to recode levels "-99" in factor vars
data <- data |> 
  mutate(across(where(is.factor), ~forcats::fct_recode(., NULL = "-99")))

# recode factor levels 
data <- data |> 
  # use `pewmethods` to preserve order of factor levels
  mutate(across(c(q19, q20, q21, q22, q23,q24, q25, q26,
                  q30, q31, q32, q33, q34, q35, q36, q37), 
                ~pewmethods::fct_case_when(
    .x == "Not at all confident" |
      .x == "Not at all committed" ~ "Not at all",
    .x == "Not too confident" |
      .x == "Not too committed"|
      .x == "Not too concerned"|
      .x == "Somewhat unconcerned" ~ "Not that much",
    .x == "Somewhat confident" |
      .x == "Somewhat committed" ~ "Somewhat",
    .x == "Very confident" |
      .x == "Very committed" ~ "Very",
    TRUE ~ NA
  )))

```

```{r}
#| label: fns
#| include: false

source(here::here('src', 'funs.R'))

```

## Demographics

```{r}
#| label: tbl-1
#| tbl-cap: "Description of Sample Demographics"
#| tbl-cap-location: top

# quick, informative, easy table of sample demographics w/ some other questions.


# best method for html document
tbl.desc <- data |>  
  labelled::set_variable_labels(
    age_4cat = "Age group, in years",
    gender_3cat = "Gender",
    race2 = "Race/Ethnicity",
    educ_4cat = "Education",
    partyid_3cat = "Party ID"
  ) |> 
  gtsummary::tbl_summary(
    by = group,
    include = c(
    age_4cat, 
    gender_3cat, 
    race2, 
    educ_4cat, 
    partyid_3cat),
    statistic = list(gtsummary::all_categorical()~ "{n} ({p}%)"), 
    missing = "ifany",
    missing_text = "NA") |> 
  gtsummary::add_n() |> 
  gtsummary::add_overall() |> 
  gtsummary::modify_header(label = "**Variable**") |> 
  gtsummary::bold_labels()


gtsummary::as_gt(tbl.desc) |>  
  gt::tab_footnote(
    footnote = "Independents do not identify nor 'lean' toward either political party",
    placement = "left"
    ) |>  
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )

gtsummary::as_kable_extra(
  tbl.desc, 
  booktabs = T,
  digits = 2,
  addtl_fmt = T,
  linesep = ""
) |> 
  kableExtra::kable_styling(
    latex_options = c("striped", "scale_down"),
    font_size = 8)





```

```{r}
#| label: tbl-1-pdf
#| tbl-cap: "Description of Sample Demographics"
#| tbl-cap-location: top

# compute counts and proportions
count_prop <- function(x, drop_na = TRUE, sort = FALSE){
  p <- data |>  
    count({{ x }})
  if (drop_na == FALSE){
    p |> 
      mutate(prop = n/sum(n))
  } else {
    p |> drop_na() |> 
      mutate(prop = n/sum(n)*100)
  }
}


frqs <- data |> 
  select(qset, age_cat, gender_3cat, educ_4cat, race, partyid_3cat) |>
  map(count_prop)

demog_df <- purrr::reduce(frqs, dplyr::full_join)


kableExtra::kbl(demog_df,
                booktabs = T, 
                digits = 2,
                col.names = c("Name", "n", "Pct")) |> 
  kableExtra::pack_rows("Qset", 1, 2) |> 
  kableExtra::pack_rows("Age", 3, 10) |> 
  kableExtra::pack_rows("Gender", 11, 13) |> 
  kableExtra::pack_rows("Education", 14, 17) |> 
  kableExtra::pack_rows("Race", 18, 22) |> 
  kableExtra::pack_rows("Party ID", 23, 25) |> 
  kableExtra::kable_styling(
    latex_options = c("striped", "scale_down"),
    full_width = F,
    font_size = 8) |> 
  kableExtra::column_spec(1, width = "20em")


```

## Summary Tables

```{r}
#| label: tbl-tc
#| tbl-cap: "Trust and Confidence in Election Administration"

# Likert table summary of Trust and confidence variables
# best method for html document
tbl.desc <- data |>  
  labelled::set_variable_labels(
    age_4cat = "Age group, in years",
    gender_3cat = "Gender",
    race2 = "Race/Ethnicity",
    educ_4cat = "Education",
    partyid_3cat = "Party ID"
  ) |> 
  gtsummary::tbl_summary(
    by = group,
    include = c(
    age_4cat, 
    gender_3cat, 
    race2, 
    educ_4cat, 
    partyid_3cat),
    statistic = list(gtsummary::all_categorical()~ "{n} ({p}%)"), 
    missing = "ifany",
    missing_text = "NA") |> 
  gtsummary::add_n() |> 
  gtsummary::add_overall() |> 
  gtsummary::modify_header(label = "**Variable**") |> 
  gtsummary::bold_labels()


gtsummary::as_gt(tbl.desc) |>  
  gt::tab_footnote(
    footnote = "Independents do not identify nor 'lean' toward either political party",
    placement = "left"
    ) |>  
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )

gtsummary::as_kable_extra(
  tbl.desc, 
  booktabs = T,
  digits = 2,
  addtl_fmt = T,
  linesep = ""
) |> 
  kableExtra::kable_styling(
    latex_options = c("striped", "scale_down"),
    font_size = 8)





```


```{r}
#| label: tbl-eef
#| tbl-cap: "Expectation of Electoral Fraud"

# Likert table summary of Expectation of electoral fraud :::::::::::::::::::####
tbl_eef <- data |> 
  select(contains("q28_")) |>
  gtsummary::tbl_likert(
    statistic = ~"{n} ({p}%)", 
    label = list(q28_1 = "There will be voter fraud",
                 q28_2 = "Many votes will not be counted",
                 q28_3 = "Voters will be turned away",
                 q28_4 = "Foreign Interference",
                 q28_5 = "Election officials will discourage some voters"))
  
# add continuous summary of Likert scores
tbl_eef_summary <- list(
  tbl_eef,
  gtsummary::tbl_wide_summary(
    data |>
      select(contains("q28_")) |> mutate(across(where(is.factor), as.numeric)),
    statistic = c("{mean}", "{sd}"), 
    label = list(q28_1 = "There will be voter fraud",
                 q28_2 = "Many votes will not be counted",
                 q28_3 = "Voters will be turned away",
                 q28_4 = "Foreign Interference",
                 q28_5 = "Election officials will discourage some voters"),
    type = ~ "continuous"
  )
) |>
  gtsummary::tbl_merge(tab_spanner = F) |> 
  gtsummary::modify_header(label="")


# print as huxtable and modify using `huxtable` R package
gtsummary::as_hux_table(tbl_eef_summary) |>
  huxtable::set_width(0.6) |> 
  huxtable::set_col_width(rep(c(0.4))) |> 
  huxtable::theme_article() |> 
  huxtable::add_footnote(border = 0.8,
    "Note: Full survey question and statement wording can be found in the appendix") |> 
  huxtable::set_position("center")




```

```{r}
#| label: tbl-safe
#| tbl-cap: "Concern for voter safety"

# Likert table summary of Concerns for Voter Safety ::::::::::::::::::::::::####
tbl_safe <- data |> 
  select(q25, q26) |>
  gtsummary::tbl_likert(
    statistic = ~"{n} ({p}%)", 
    label = list(q25 = "Potential for violence, threats, or intimidation",
                 q26 = "Polling sites will be safe for voters"))
  
# add continuous summary of Likert scores
tbl_safe_summary <- list(
  tbl_safe,
  gtsummary::tbl_wide_summary(
    data |>
      select(q25, q26) |> mutate(across(where(is.factor), as.numeric)),
    statistic = c("{mean}", "{sd}"),  
    label = list(q25 = "Potential for violence, threats, or intimidation",
                 q26 = "Polling sites will be safe for voters"),
    type = ~ "continuous"
  )
) |>
  gtsummary::tbl_merge(tab_spanner = F) |> 
  gtsummary::modify_header(label="**Concern**")


# print as huxtable and modify using `huxtable` R package
gtsummary::as_hux_table(tbl_safe_summary) |>
  huxtable::set_width(0.6) |> 
  huxtable::set_col_width(rep(c(0.4))) |> 
  huxtable::theme_article() |> 
  huxtable::add_footnote(border = 0.8,
    "Note: Full survey question and statement wording can be found in the appendix") |> 
  huxtable::set_position("center")

```


## Crosstables

```{r}
#| label: tbl-q19
#| tbl-cap: "Confidence vote counts will be accurate in Maricopa County, AZ by Experiment Condition"

# Crosstab of Q19 by treatment group
data |> 
  janitor::tabyl(group, q19, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q19') |>
  gt::gt(
    rowname_col = 'Q19',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q19') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Q19. Vote Count Confidence for Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q19. How confident are you that votes in Maricopa County, AZ will be counted as voters intend in the elections this November?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )

# df |> 
#   janitor::tabyl(group, q19, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q19') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )


```

```{r}
#| label: tbl-q21
#| tbl-cap: "Election Staff Commitment to Fairness and Accuracy by Experiment Condition"
#| tbl-cap-location: top


data |> 
  janitor::tabyl(group, q21, show_na = F) |> 
  # janitor::adorn_totals("both") |> 
  janitor::adorn_percentages("row") |> 
  janitor::adorn_pct_formatting(digits = 2, affix_sign = F) |>
  janitor::adorn_ns("rear") |> 
  janitor::adorn_title("combined", 
                       row_name = "Group",
                       col_name = "Q21") |>
  # bind_rows(.id = "group_var") |>   
  gt::gt(
    rowname_col = "row_var",
    groupname_col = "group_var") |>   
  gt::cols_label(
    c('Group/Q21') ~ "Group") |>
  # gt::cols_label_with(columns = '...1', fn = ~sjlabelled::get_label(df$q5.clps)) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Q21. Election staff commitment to fairness and accuracy"
  ) |>
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q21. Think about the election staff and volunteers who handle the administration and conduct of elections in Maricopa County, AZ. How committed do you think they will be to making sure the elections held this November are fair and accurate?",
    locations = gt::cells_column_spanners()) |>
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )

# df |> 
#   janitor::tabyl(group, q21, show_na = F) |> 
#   janitor::adorn_totals("both") |> 
#   janitor::adorn_percentages("row") |> 
#   janitor::adorn_pct_formatting(digits = 2, affix_sign = F) |>
#   janitor::adorn_ns("rear") |> 
#   janitor::adorn_title("combined", 
#                        row_name = "Group",
#                        col_name = "Q21")



```


```{r}
#| label: tbl-q22
#| tbl-cap: "Q22. Confidence in Fair Voting Process by Experiment Condition in Maricopa County, AZ by Experiment Condition"
#| tbl-cap-location: top

# Crosstab of Q22 by treatment group
df |> 
  janitor::tabyl(group, q22, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q22') |>
  gt::gt(
    rowname_col = 'Q22',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q22') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Q22. Confidence in Fair Voting Process for Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q22.How confident are you that the voting process will be fair in Maricopa County, AZ?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )



# df |> 
#   janitor::tabyl(group, q22, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q22') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )


```

```{r}


df |> 
  janitor::tabyl(q7, q22, group, show_na = F) |> 
  # janitor::adorn_totals("both") |>
  janitor::adorn_percentages("row") |> 
  janitor::adorn_pct_formatting(digits = 2, affix_sign = F) |>
  janitor::adorn_ns("rear") |> 
  janitor::adorn_title("combined", 
                       row_name = "Q7. Legitimacy of 2020 Election",
                       col_name = "Q22") |>
  bind_rows(.id = "group_var") |>   
  gt::gt(
    rowname_col = "row_var",
    groupname_col = "group_var") |>  
  gt::row_group_order(groups = c("Control", "Treatment")) |> 
  gt::cols_label(
    c('Q7. Legitimacy of 2020 Election/Q22') ~ "Q7. Legitimacy of 2020 Election") |>
  # gt::cols_label_with(columns = '...1', fn = ~sjlabelled::get_label(df$q5.clps)) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 3:6,
    label = "Q22. Confidence in Fair Voting process for Maricopa County, AZ"
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q22.How confident are you that the voting process will be fair in Maricopa County, AZ?",
    locations = gt::cells_column_spanners()) |> 
  gt::tab_footnote(
    footnote = "Q7.Regardless of whom you supported in the 2020 election, \ndo you think Joe Biden's election as president was legitimate, or was he not legitimately elected?",
    locations = gt::cells_column_labels('Q7. Legitimacy of 2020 Election/Q22')
    ) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )
```




```{r}
#| label: tbl-q23
#| tbl-cap: "q23. Confidence in Fair Voting Process by Experiment Condition in Maricopa County, AZ by Experiment Condition"
#| tbl-cap-location: top

# Crosstab of q23 by treatment group
df |> 
  janitor::tabyl(group, q23, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q23') |>
  gt::gt(
    rowname_col = 'Q23',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q23') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Q23. Confidence in Fair Voting Outcomesfor Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q23.How confident are you that the voting outcomes will be fair in Maricopa County, AZ?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )



# df |> 
#   janitor::tabyl(group, q23, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'q23') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )


```

```{r}


df |> 
  janitor::tabyl(q7, q23, group, show_na = F) |> 
  # janitor::adorn_totals("both") |> 
  janitor::adorn_percentages("row") |> 
  janitor::adorn_pct_formatting(digits = 2, affix_sign = F) |>
  janitor::adorn_ns("rear") |> 
  janitor::adorn_title("combined", 
                       row_name = "Q7. Legitimacy of 2020 Election",
                       col_name = "Q23") |>
  bind_rows(.id = "group_var") |>   
  gt::gt(
    rowname_col = "row_var",
    groupname_col = "group_var") |>  
  gt::row_group_order(groups = c("Control", "Treatment")) |> 
  gt::cols_label(
    c('Q7. Legitimacy of 2020 Election/Q23') ~ "Q7. Legitimacy of 2020 Election") |>
  # gt::cols_label_with(columns = '...1', fn = ~sjlabelled::get_label(df$q5.clps)) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 3:6,
    label = "Q23. Confidence in Fair Voting Outcomesfor Maricopa County, AZ"
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q23.How confident are you that the voting outcomes will be fair in Maricopa County, AZ?",
    locations = gt::cells_column_spanners()) |> 
  gt::tab_footnote(
    footnote = "Q7.Regardless of whom you supported in the 2020 election, \ndo you think Joe Biden's election as president was legitimate, or was he not legitimately elected?",
    locations = gt::cells_column_labels('Q7. Legitimacy of 2020 Election/Q23')
    ) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )
```

```{r}
#| label: tbl-q24-crab
#| tbl-cap: "q24. Confidence in Fair Voting Process by Experiment Condition in Maricopa County, AZ by Experiment Condition"
#| tbl-cap-location: top

# Crosstab of q24 by treatment group
df |> 
  janitor::tabyl(group, q24, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q24') |>
  gt::gt(
    rowname_col = 'Q24',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q24') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Q24. Confidence in Fair Voting Outcomesfor Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q24.How confident are you that the voting outcomes will be fair in Maricopa County, AZ?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )



# df |>
#   janitor::tabyl(group, q24, show_na = F) |>
#   janitor::adorn_totals('both', na.rm = T) |>
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |>
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'q24') |>
#   kableExtra::kbl() |>
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )


```


```{r}
#| label: tbl-q25-crab
#| tbl-cap: "Concern for violence, threats, or voter intimidation in Maricopa County, AZ by Experiment Condition"
#| tbl-cap-location: top


# Crosstab of Q25 by treatment group
df |> 
  janitor::tabyl(group, q25, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q25') |>
  gt::gt(
    rowname_col = 'Q25',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q25') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Concern for violence, threats, or voter intimidation in Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q25. Thinking about Maricopa County, AZ, how concerned should voters feel \nabout potential violence, \nthreats of violence, or intimidation while voting in person at their local polling place?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )



# alternative crosstab
# df |> 
#   janitor::tabyl(group, q25, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q25') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )


```

```{r}
#| label: tbl-q26-crab
#| tbl-cap: "Q26. In-person voter safety in Maricopa County, AZ by Experiment Condition"
#| tbl-cap-location: top

# Crosstab of Q26 by treatment group
df |> 
  janitor::tabyl(group, q26, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q26') |>
  gt::gt(
    rowname_col = 'Q26',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q26') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Confidence for In-person voter safety in Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q26. How confident, if at all, are you that in person polling places in Maricopa County, AZ \nwill be safe places for voters to cast their ballots during the upcoming elections in November?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )



# df |> 
#   janitor::tabyl(group, q26, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q26') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )

```

```{r}
#| label: tbl-q27-crab
#| tbl-cap: "Q27. Approval for Election official in Maricopa County, AZ"
#| tbl-cap-location: top


df |> 
  janitor::tabyl(group, q27, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q27') |>
  gt::gt(
    rowname_col = 'Q27',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q27') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Approval for Election official in Maricopa County, AZ"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q27. Do you approve or disapprove of the way election officials in Maricopa County, AZ are handling their jobs?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )


# df |> 
#   janitor::tabyl(group, q27, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q27') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )



```

```{r}
#| label: tbl-q29-crab
#| tbl-cap: "Q29. Should Local Area Adopt Recruitment Program of Maricopa County, AZ"
#| tbl-cap-location: top


df |> 
  janitor::tabyl(group, q29, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q29') |>
  gt::gt(
    rowname_col = 'Q29',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q29') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Should Local Community Adopt Maricopa County, AZ Recruitment Program"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q29. How much would you like to see your local community adopt a program for recruiting elections staff like the one you read about in Maricopa County, AZ?",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )




# df |> 
#   janitor::tabyl(group, q29, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q29') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )



```

```{r}


df |> 
  janitor::tabyl(group, q41.4, show_na = F) |>
  janitor::adorn_percentages(denominator = 'row') |>
  janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
  janitor::adorn_ns() |> 
  janitor::adorn_title(
    'combined',
    row_name = "Group",
    col_name = 'Q41.4') |>
  gt::gt(
    rowname_col = 'Q41.4',
    groupname_col = 'Group' 
  ) |>  
  gt::cols_label(
    c('Group/Q41.4') ~ "Group") |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_row_groups()
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_labels()
  ) |> 
  gt::tab_spanner(
    columns = 2:5,
    label = "Election staff and volunteers include military veterans and their family members"
  ) |>  
  gt::tab_style(
    style = gt::cell_text(weight = 'bold'),
    locations = gt::cells_column_spanners()
    ) |> 
  gt::tab_footnote(
    footnote = "Table reflects row percentages. NAs omitted") |> 
  gt::tab_footnote(
    footnote = "Q41.4. How would the following impact your confidence in the fairness and accuracy of elections conducted this November? Election staff and volunteers include military veterans and their family members from the community",
    locations = gt::cells_column_spanners()) |> 
  gt::cols_align(align = 'left', columns = everything()) |> 
  gt::tab_options(
    table.font.size = "small",
    data_row.padding = gt::px(1)
  )

# "Regardless of whether any of these are actually the case, how would the following impact your confidence in the fairness and accuracy of elections conducted this November?"
# Election staff and volunteers include military veterans and their family members from the community.


# df |> 
#   janitor::tabyl(group, q29, show_na = F) |>  
#   janitor::adorn_totals('both', na.rm = T) |> 
#   janitor::adorn_percentages(denominator = 'row') |>
#   janitor::adorn_pct_formatting(digits = 1, affix_sign = F) |>
#   janitor::adorn_ns() |> 
#   janitor::adorn_title(
#     'combined',
#     row_name = "Group",
#     col_name = 'Q29') |> 
#   kableExtra::kbl() |> 
#   kableExtra::kable_styling(
#     bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
#     latex_options = "basic",
#     font_size = 13
#   )


```

```{r}
#| label: tbl-7
#| tbl-cap: "Confidence Impact on In-person Voter Safety"
#| results: asis


# Simple Crosstab to show response breakdown by experiment condition
# NAs omitted. 
df |>
  mutate(
    confimpct_vets = dplyr::case_when(
      q43.4.clps == "increase" ~ 'Increase Confidence',
      q43.4.clps == "no_impact" ~ 'No Impact',
      q43.4.clps == 'decrease' ~ 'Decrease Confidence'
      )) |> 
  janitor::tabyl(group, confimpct_vets,  show_na = F) |> 
  janitor::adorn_totals('both') |> 
  janitor::adorn_percentages('row') |> 
  janitor::adorn_pct_formatting(digits = 2, affix_sign = T) |> 
  janitor::adorn_ns("rear") |> 
  janitor::adorn_title(
    'combined',
    row_name = 'Condition',
    col_name = 'Election staff include veterans and family') |>
  dplyr::relocate(
    "No Impact", .before = "Increase Confidence"
  ) |> 
  kableExtra::kbl() |> 
  kableExtra::footnote(
    general = "NA omitted. % (n)"
    ) |> 
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "bordered", "condensed", "responsive"),
    latex_options = "basic",
    font_size = 13,
    full_width = T,
    fixed_thead = T
  )
  



```
