---
title: "Appendix A: Survey Experiment Vignettes and Survey Items"
format:
  bookup-html: 
    toc: true
    toc-depth: 3
    embed-resources: false
    embed-fonts: true
    link-citations: true
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: false
    code-fold: show
    code-overflow: wrap
    code-tools: true
    theme: 
      light: [bookup.scss]
      dark: [bookup.scss, bookup_dark.scss]
---

## Survey Experiment Vignettes

::::: {#fig-vignettes .content-visible layout-ncol="2" when-format="html" unless-format="pdf"}
::: {#fig-treatment}
### Treatment Vignette

| **Local Military Veterans Recruited for Election Jobs in Maricopa County**
| 
|   PHOENIX (AP) — Election officials in Maricopa County, Arizona, announced a program designed to recruit military veterans and their family members from the community to serve as election administrators, including election polling place workers, temporary workers, and full-time staff. As the U.S. general elections in November near, election officials must fill several thousand temporary positions and hundreds of other open positions to ensure sufficient staffing for the 2024 elections and beyond.
| 
|   Army veteran Jordan Braxton just joined the elections workforce. Jordan believes their role is important to ensuring a secure, accurate, and transparent election, “Many places are short on staff this election cycle. I served my country in the Army, and I want to do my part as a veteran and a citizen to ensure that everyone trusts the process and the outcome of the election.”
:::

::: {#fig-control}
### Control Vignette

| **Local Residents Recruited for Election Jobs in Maricopa County**
| 
|   PHOENIX (AP) —Election officials in Maricopa County, Arizona, announced a program to recruit members of the community to serve as election administrators, including election polling place workers, temporary workers, and full-time staff. As the U.S. general elections in November near, election officials must fill several thousand temporary positions and hundreds of other open positions to ensure sufficient staffing for the 2024 elections and beyond.
| 
|   Jordan Braxton just joined the elections workforce. Jordan believes their role is important to ensuring a secure, accurate, and transparent election, “Many places are short on staff this election cycle. I want to do my part as a citizen to ensure that everyone trusts the process and the outcome of the election.”
:::

Fabricated Article Vignettes utilized as Experimental Stimulus
:::::

::::: {.content-hidden unless-format="pdf" layout="[0.45, -0.1, 0.45]"}
::: {#first-column}
### Treatment Vignette

| **Local Military Veterans Recruited for Election Jobs in Maricopa County**
| 
|   PHOENIX (AP) — Election officials in Maricopa County, Arizona, announced a program designed to recruit military veterans and their family members from the community to serve as election administrators, including election polling place workers, temporary workers, and full-time staff. As the U.S. general elections in November near, election officials must fill several thousand temporary positions and hundreds of other open positions to ensure sufficient staffing for the 2024 elections and beyond.
| 
|   Army veteran Jordan Braxton just joined the elections workforce. Jordan believes their role is important to ensuring a secure, accurate, and transparent election, “Many places are short on staff this election cycle. I served my country in the Army, and I want to do my part as a veteran and a citizen to ensure that everyone trusts the process and the outcome of the election.”
:::

::: {#second-column}
### Control Vignette

| **Local Residents Recruited for Election Jobs in Maricopa County**
| 
|   PHOENIX (AP) —Election officials in Maricopa County, Arizona, announced a program to recruit members of the community to serve as election administrators, including election polling place workers, temporary workers, and full-time staff. As the U.S. general elections in November near, election officials must fill several thousand temporary positions and hundreds of other open positions to ensure sufficient staffing for the 2024 elections and beyond.
| 
|   Jordan Braxton just joined the elections workforce. Jordan believes their role is important to ensuring a secure, accurate, and transparent election, “Many places are short on staff this election cycle. I want to do my part as a citizen to ensure that everyone trusts the process and the outcome of the election.”
:::
:::::

\newpage

## Survey Items

```{r}
#| label: tbl-4
#| tbl-cap: "Survey Items and Response Options"

df |> 
  select(q6, q7, q25, q26) |> 
  labelled::generate_dictionary() |> 
  dplyr::as_tibble() |> 
  mutate(value_labels = dplyr::case_when(
    variable == 'q6' ~ "[Strongly unfavorable, Somewhat unfavorable, Neither, Somewhat favorable, Strongly favorable]",
    variable == 'q7' ~ "Legitimate, Not legitimate",
    variable == 'q25' ~ "Very concerned, Somewhat concerned, Not too concerned, Not at all concerned",
    variable == 'q26' ~ "Not at all confident, Not too confident, Somewhat confident, Very confident"
  )) |> 
  select(Question = label, response = value_labels) |> 
  kableExtra::kbl(booktabs = T, linesep = "\\addlinespace") |> 
  kableExtra::kable_styling(full_width = T,
                            font_size = 8,
                            latex_options = c("HOLD_position")) |> 
  kableExtra::column_spec(column = 1, width = "7cm") |> 
  kableExtra::column_spec(column = 2, width = "4cm")


```




